package:
  name: libx11-cos7-armv7l
  version: 1.6.5

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libX11-1.6.5-2.el7.armv7hl.rpm
    sha256: 258d7f570aab70688bd9f5876e012ac4d481661224887c3455f5ce460aacacb4
    folder: binary
  - url: http://vault.centos.org/7.6.1810/os/Source/SPackages/libX11-1.6.5-2.el7.src.rpm
    folder: source

build:
  number: 0
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-common-cos7-armv7l >=1.6.5


outputs:
  - name: libx11-cos7-armv7l
    build:
      noarch: generic
    requirements:
      run:
        - libx11-common-cos7-armv7l >=1.6.5

    about:
      home: http://www.x.org
      license: MIT
      license_family: MIT
      summary: "(CDT) Core X11 protocol client library"
      description: |
        Core X11 protocol client library.
