package:
  name: xorg-x11-proto-devel-cos7-armv7l
  version: 2018.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/xorg-x11-proto-devel-2018.4-1.el7.noarch.rpm
    sha256: ed33c07dd19aae73edaef6cb5daeca44fae87aa7fba16d5de6aad4c244f5232f
    folder: binary
  - url: http://vault.centos.org/7.6.1810/os/Source/SPackages/xorg-x11-proto-devel-2018.4-1.el7.src.rpm
    folder: source

build:
  number: 0
  missing_dso_whitelist:
    - '*'



outputs:
  - name: xorg-x11-proto-devel-cos7-armv7l
    build:
      noarch: generic

    about:
      home: https://www.x.org
      license: MIT
      license_family: MIT
      summary: "(CDT) X.Org X11 Protocol headers"
      description: |
        X.Org X11 Protocol headers
