# cos7-specific because of PYTHON_SYSCONFIGDATA_NAME below.  Would be nice to make that more generic if possible.
ctng_target_platform:
  - linux-armv7l
FINAL_CPPFLAGS:
  - -DNDEBUG -D_FORTIFY_SOURCE=2 -O2
FINAL_CFLAGS:
  - -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_FFLAGS:
  - -fopenmp -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_LDFLAGS:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections
FINAL_DEBUG_CPPFLAGS:
  - -D_DEBUG -D_FORTIFY_SOURCE=2 -Og
FINAL_DEBUG_CFLAGS:
  - -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_DEBUG_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_DEBUG_FFLAGS:
  - -fopenmp -march=armv7-a -mfpu=vfpv3-d16 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_armv7l_conda_cos7_linux_gnu
ctng_gcc:
  - 8.3.0
ctng_binutils:
  - 2.29.1
ctng_gcc_activation_build_num:
  - 0
