{% set version = "0.22.0" %}

package:
  name: asn1crypto
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-{{ version }}.tar.gz
  sha256: cbbadd640d3165ab24b06ef25d1dca09a3441611ac15f6a6b452474fdf0aed1a

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asn1crypto

about:
  home: https://github.com/wbond/asn1crypto
  license: MIT
  license_file: LICENSE
  summary: Python ASN.1 library with a focus on performance and a pythonic API

extra:
  recipe-maintainers:
    - jschueller
    - ocefpaf
