{% set version = "1.9.2" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: 72b5f1aea9101cf720a36bb2327ede866fd6f1a07b1e87c92a1cc18113cbc946

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - backports.functools_lru_cache  # [py<33]

test:
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup 

extra:
  recipe-maintainers:
    - jschueller
