package:
  name: crosstool-ng
  version: 1.24.0

source:
  url: http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.bz2
  sha256: d200d1ea5e2056c60d2b11b3f2721d30e53e817e1e0050fffaca074864e2f523

build:
  number: 0
  missing_dso_whitelist:
    - '*'

# no requirements, this is built using system tools

test:
  commands:
    - ct-ng -h

about:
  home: http://crosstool-ng.org/

extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - jjhelmus
